language: c
os:
    - linux
    - osx

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
compiler:
    - gcc
    - clang

env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "Oxi8cvDfADl7IqM5riGSQ+0d1KIUmtCJqvIdxv719l6DoatPEAhePwh1gMtwy+UckMKJvbMGBh7a2YhjR+uODXW9uDe3csgGT4MpcFbPe3M0+K+Jj/vLGAWtVbcrIJiet6JK6nDotsU8r2TBxn/vIFeR7er+dhyP1ZDQJ0PbaHq/IjuvPQK3TQQwD5/ocrFMVb0UJT7TArx5J40dvwUbADaRRycgWrmbk3vZzkT3PSOTE9BzjTw/MyXuBAxx/opJBw4FTCSJbcLzdkDo26mK+b8WjUSCrUxvXt/6dhs+Z8LoBvEOrIYlUX7qoU+YFuFnMBbVDbwiSf40T7edgCDesnwRQa1E8u3M7rQhPXF9L8aQ9oTsER9tLYne8J1zIcSg3fCyrfMytNb3OzDYU9OtA5Yr8y5kkigLRL0mUcPsi+9Ysj0YioqBgcc1WZXXAkYH+DvCxDzEU5W2Qr6vrxOGHKLnVyz4vltca2hpTZhxVhZ4/N9jTdIN9cPTmDwnv8V7mXonpHCmSYW2JcR3tzm3JNCuooLbNZBPSxmfHLcW7UQmVod+cpZ1cCbe0Zu7S8lD51EzoX+1uPyBwo2RTF/CCcGDziyQV9PF0xhsylm7BqVuoW9siZnW2UBJjA0EzkmKvmDdjqJGCqmbPvpDutLGWi5AfhnQzZvkhEYUwzszN3Y="

addons:
  coverity_scan:
    project:
      name: "Comcast/aker"
      description: "  Aker is an experimental MAC address blocking scheduler."
    notification_email: weston_schmidt@alumni.purdue.edu
    build_command_prepend: "mkdir coverity_build && cd coverity_build && cmake .."
    build_command: "make"
    branch_pattern: main

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install cunit md5sha1sum; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov valgrind; fi

install:

script:
    - mkdir build
    - cd build
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then cmake .. -DDISABLE_VALGRIND:BOOL=true; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi
    - make
    - make test

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov; fi
